sudo: required
dist: trusty
language: node_js

node_js:
  - "7"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
install:
  - cd showdown-angular4
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://aaradhanas.github.io/angular/
  
deploy:
   - github_token: $GITHUB_TOKEN
   - ngh