language: node_js

node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - cd showdown-angular4
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --base-href https://aaradhanas.github.io/angular/
  - ngh --repo https://github.com/aaradhanas/angular