addons:
  firefox: "49.0"

language: node_js

node_js:
  - "7"

branches:
  only:
    - master
  
install:
  - cd FAQApp
  - npm install
  - cd ../showdown-angular4
  - npm install
  - npm install -g angular-cli-ghpages
   

script:
  - ng lint
  - ng build --prod --base-href https://aaradhanas.github.io/angular/
  - cd ../FAQApp
  - ng build --prod
  - ng lint
  - ng test