language: node_js

node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - cd showdown-angular4
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --base-href https://aaradhanas.github.io/angular/
  - ngh --repo https://d2310bc43482d163a2bfb8537d4c3084aa1a787e@github.com/aaradhanas/angular.git --no-silent