language: node_js

node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - cd ClientPanel
  - npm install
  - cd ../FAQApp
  - npm install
  - cd ../showdown-angular4
  - npm install

script:
  - cd ClientPanel
  - ng build --aot
  - cd ../FAQApp
  - ng build --aot
  - cd ../showdown-angular4
  - ng build --aot